/*
 * This file is generated by jOOQ.
 */
package com.rameshputalapattu.tstracker.jooq.model;


import com.rameshputalapattu.tstracker.jooq.model.tables.SqliteSequence;
import com.rameshputalapattu.tstracker.jooq.model.tables.Timesheet;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>timesheet</code>.
     */
    public final Timesheet TIMESHEET = Timesheet.TIMESHEET;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            SqliteSequence.SQLITE_SEQUENCE,
            Timesheet.TIMESHEET
        );
    }
}
