/*
 * This file is generated by jOOQ.
 */
package com.rameshputalapattu.tstracker.jooq.model;


import com.rameshputalapattu.tstracker.jooq.model.tables.Timesheet;
import com.rameshputalapattu.tstracker.jooq.model.tables.records.TimesheetRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in ts.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TimesheetRecord> TIMESHEET_PKEY = Internal.createUniqueKey(Timesheet.TIMESHEET, DSL.name("timesheet_pkey"), new TableField[] { Timesheet.TIMESHEET.ID }, true);
}
