/*
 * This file is generated by jOOQ.
 */
package com.rameshputalapattu.tstracker.jooq.model;


import com.rameshputalapattu.tstracker.jooq.model.tables.SqliteSequence;
import com.rameshputalapattu.tstracker.jooq.model.tables.Timesheet;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>timesheet</code>.
     */
    public static final Timesheet TIMESHEET = Timesheet.TIMESHEET;
}
