/*
 * This file is generated by jOOQ.
 */
package com.rameshputalapattu.tstracker.jooq.model;


import com.rameshputalapattu.tstracker.jooq.model.tables.Timesheet;


/**
 * Convenience access to all tables in ts.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ts.timesheet</code>.
     */
    public static final Timesheet TIMESHEET = Timesheet.TIMESHEET;
}
