/*
 * This file is generated by jOOQ.
 */
package com.rameshputalapattu.tstracker.jooq.model;


import com.rameshputalapattu.tstracker.jooq.model.tables.Timesheet;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ts extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ts</code>
     */
    public static final Ts TS = new Ts();

    /**
     * The table <code>ts.timesheet</code>.
     */
    public final Timesheet TIMESHEET = Timesheet.TIMESHEET;

    /**
     * No further instances allowed
     */
    private Ts() {
        super("ts", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Timesheet.TIMESHEET
        );
    }
}
